### ISSUE TITLE
Please don't hide also the wings

### ISSUE THREAD

**Issue by Carlokxdxdxd** [fixyldev/InvisibleArmorModel#4]
USING ARMOR:
![image](https://github.com/user-attachments/assets/0f2ec19c-c5b2-477d-99fc-7c6d7edc09c8)
![image](https://github.com/user-attachments/assets/3509c136-2f76-4c43-a4b3-c93b55414609)

NOT USING ARMOR:
![image](https://github.com/user-attachments/assets/6d652e84-19b9-4bf2-b820-16abbda83227)
![image](https://github.com/user-attachments/assets/1350766a-5e64-4c77-9993-afbd577f019f)

PS: I ALSO TRIED OTHER BACK ITEMS IN CHARACTER SETTINGS; IT WON'T SHOW MY OWN BACK ITEM SKIN

Please fix it. Thank you! ♥

**Comment by fixyldev** [comment]
Thanks for your bug report! I know why this happens but I don't know if I'm able to fix this or if this can even be fixed. I'm not that well when it comes to Minecraft Bedrock Editon. But I will look into this.

**Comment by fixyldev** [comment]
Sadly, I don't think this is possible to fix. The rendering of back items like wings is probably tied to whether a chestplate is equipped, not whether the chestplate actually renders. If I'm wrong, someone can point that out in the future, but for now, this won't be fixed.
